/-
  Slice 3e — the CAP-OUT-LINK / Link≅geom checkers over the Aeneas-lifted model.

  `CertifyCore.Funs` is generated by charon→aeneas **directly from the real
  `crates/certify-core/src/arrange.rs`** link checkers (`v_boundary`, `link_ok`,
  `link_iso_ok`, and their closure `classify_link` / `cyclic_true_runs` / `all_true`).
  It typechecks against the Aeneas Lean library, so `certify-core` is a genuine second
  extraction surface — and, unlike `lattice::small`, it needs **no** hand-written
  externals (its `FunsExternal.lean` is empty), so its lifted TCB is exactly
  Charon + Aeneas + Lean, nothing bespoke.

  What is proven here (the tractable, deductive part of the 3e ★ soundness, complementing
  the bounded Kani proofs `link_ok_iff_no_pinch` / `link_iso_matches_cyclic_adjacency`):

  * `link_ok_rejects_pinch` — the lifted `link_ok` returns `false` **iff** the vertex
    classifies as `Pinch`. So acceptance is exactly "not a non-manifold pinch" — the
    CAP-OUT-LINK reject rule (spec §8.5 "disconnected ⇒ reject"), as a Lean theorem over
    the extracted model.
  * `v_boundary_imp_link_ok` — every `V_∂` boundary vertex passes the manifold check
    (`V_∂ ⊆ accepted`): the emitted-shell-vertex set is manifold by construction.
  * `v_boundary_and_link_ok_iff` — the two link predicates in terms of the classifier.
  * `#print axioms` — the lifted checkers are `sorry`-free (off the Aeneas Std
    `get_unchecked`/StringIter sorries).

  These are the **dispatch-soundness** layer — the V_∂ / manifold logic over the
  classifier — proven without the loop refinement of `cyclic_true_runs`. The remaining
  frontier (documented, not gating): the run-counter refinement
  (`cyclic_true_runs = the cyclic-run count`, hence `link_ok ↔ ≤1 run` matching the Kani
  property) via `loop.spec_decr_nat`, and above it the topological
  `CAP-OUT-LINK-at-every-vertex ⇒ 2-manifold-with-boundary` theorem.
-/
import CertifyCore.Funs

open Aeneas Aeneas.Std Result

namespace CertifyCheck
open certify_core

/-- The lifted `link_ok` returns `false` **iff** the classification is a `Pinch`
    (spec §8.5: CAP-OUT-LINK rejects exactly the non-manifold pinch). Dispatch
    soundness — independent of the run counter `cyclic_true_runs`. -/
theorem link_ok_rejects_pinch (s : Slice Bool) :
    arrange.link_ok s = ok false ↔
      arrange.classify_link s = ok arrange.LinkClass.Pinch := by
  unfold arrange.link_ok
  cases hc : arrange.classify_link s with
  | ok lc => cases lc <;> simp
  | fail e => simp
  | div => simp

/-- `v_boundary` returns `true` **iff** the classification is `Boundary` (spec §8.5:
    `v ∈ V_∂` iff the selected sectors form one proper cyclic interval). -/
theorem v_boundary_iff_boundary (s : Slice Bool) :
    arrange.v_boundary s = ok true ↔
      arrange.classify_link s = ok arrange.LinkClass.Boundary := by
  unfold arrange.v_boundary
  cases hc : arrange.classify_link s with
  | ok lc => cases lc <;> simp
  | fail e => simp
  | div => simp

/-- **Every V_∂ boundary vertex passes the manifold check** (`V_∂ ⊆ accepted`): a
    `Boundary` vertex is never a `Pinch`, so `v_boundary ⇒ link_ok`. The emitted shell
    vertices are manifold by construction. -/
theorem v_boundary_imp_link_ok (s : Slice Bool) :
    arrange.v_boundary s = ok true → arrange.link_ok s = ok true := by
  intro h
  have hb : arrange.classify_link s = ok arrange.LinkClass.Boundary :=
    (v_boundary_iff_boundary s).mp h
  unfold arrange.link_ok
  simp [hb]

-- The lifted checkers carry no `sorry` (the Aeneas Std sorries are on
-- `get_unchecked`/`StringIter`, off this slice-index path).
#print axioms arrange.link_ok
#print axioms arrange.v_boundary
#print axioms arrange.link_iso_ok

end CertifyCheck
