/-
  Phase 1, Aeneas route — the Aeneas-lifted `sign_variations` model, integrated.

  `Lattice.Funs` is generated by charon→aeneas **directly from the real
  `crates/lattice/src/sturm.rs::sign_variations`** (not a copy — the emitted
  `Source` comments cite that file, lines 26–38). It typechecks against the Aeneas
  Lean library, so the full Rust → LLBC → Lean pipeline is end-to-end on this
  platform, over actual repo code.

  The emitted model (`lattice.sturm.sign_variations : Slice I8 → Result U32`) is a
  `loop` over the concrete slice iterator (`IteratorSliceIter.next`, a total
  index-based step — no `sorry`, no `get_unchecked`), in the `Result` monad
  (fallible only via the `v + 1#u32` overflow check).

  What is proven here:
  * `lifted_sign_variations_eq_loop` — the lift reduces to its loop over the
    iterator at index 0 with the sentinel accumulator (definitional).
  * The generated definition is `sorry`-free (`#print axioms` below).

  The loop-invariant refinement
  `lattice.sturm.sign_variations signs ⦃ r => r.val = signVariations (sliceInts signs) ⦄`
  is **proven** in `CertifyCheck.Refine` (`sign_variations_spec`), the intended
  Aeneas way — `Aeneas.Std.loop.spec_decr_nat` for the loop + the `step` tactic for
  the body (measure `len − i`; invariant `v + svAux last (drop i) = svAux 0 I`; the
  `U32` overflow discharged by `signs.length ≤ U32.max`) — then chained to the
  mathematical spec through `signVariationsImp_eq_signVariations`. It is axiom-clean
  (`[propext, Classical.choice, Quot.sound]`; no `sorryAx`, and off the Aeneas Std
  `get_unchecked` sorries). Closing it required supplying the one `@[step]` `next`
  spec Aeneas's library omits for the shared-slice iterator (see `Refine`).
-/
import Lattice.Funs
import CertifyCheck.SignVariations

open Aeneas Aeneas.Std

namespace CertifyCheck

/-- Spec-side image of the lifted slice: each `I8` as its `Int` value (matching the
    lattice's `Rat::sign` domain and the `signVariations` argument type). -/
def sliceInts (s : Slice Std.I8) : List Int := s.val.map (fun b => b.val)

/-- The Aeneas-lifted `sign_variations` reduces to its loop over the iterator
    starting at index 0 with the `(last, v) = (0, 0)` sentinel accumulator. -/
theorem lifted_sign_variations_eq_loop (signs : Slice Std.I8) :
    lattice.sturm.sign_variations signs
      = lattice.sturm.sign_variations_loop ⟨signs, 0#usize⟩ 0#i8 0#u32 := by
  simp [lattice.sturm.sign_variations,
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter]

-- The generated model carries no `sorry` (the Aeneas Std `sorry`s are confined to
-- `get_unchecked`, off this iterator/loop path).
#print axioms lattice.sturm.sign_variations

end CertifyCheck
