-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [certify_core]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [lattice::rat::Rat]
    Source: 'crates/lattice/src/rat.rs', lines 223:0-223:35
    Name pattern: [lattice::rat::Rat]
    Visibility: public -/
@[rust_type "lattice::rat::Rat"]
axiom lattice.rat.Rat (B : Type) (Clause0_Int : Type) (Clause0_Rat : Type) :
  Type

