-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [certify_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import CertifyCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open certify_core

/-- [core::cmp::{impl core::cmp::PartialEq<core::cmp::Ordering> for core::cmp::Ordering}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 398:43-398:52
    Name pattern: [core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq]
    Visibility: public -/
@[rust_fun
  "core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq"]
axiom core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq
  : Ordering → Ordering → Result Bool

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [lattice::rat::{lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}::from_i128]:
    Source: 'crates/lattice/src/rat.rs', lines 257:4-257:37
    Name pattern: [lattice::rat::{lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>}::from_i128]
    Visibility: public -/
@[rust_fun
  "lattice::rat::{lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>}::from_i128"]
axiom lattice.rat.Rat.from_i128
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type} (backendBackendInst :
  lattice.backend.Backend B Clause0_Int Clause0_Rat) :
  Std.I128 → Result (lattice.rat.Rat B Clause0_Int Clause0_Rat)

/-- [lattice::rat::{lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}::sub]:
    Source: 'crates/lattice/src/rat.rs', lines 287:4-287:39
    Name pattern: [lattice::rat::{lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>}::sub]
    Visibility: public -/
@[rust_fun
  "lattice::rat::{lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>}::sub"]
axiom lattice.rat.Rat.sub
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type} (backendBackendInst :
  lattice.backend.Backend B Clause0_Int Clause0_Rat) :
  lattice.rat.Rat B Clause0_Int Clause0_Rat → lattice.rat.Rat B Clause0_Int
    Clause0_Rat → Result (lattice.rat.Rat B Clause0_Int Clause0_Rat)

/-- [lattice::rat::{lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}::neg]:
    Source: 'crates/lattice/src/rat.rs', lines 323:4-323:29
    Name pattern: [lattice::rat::{lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>}::neg]
    Visibility: public -/
@[rust_fun
  "lattice::rat::{lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>}::neg"]
axiom lattice.rat.Rat.neg
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type} (backendBackendInst :
  lattice.backend.Backend B Clause0_Int Clause0_Rat) :
  lattice.rat.Rat B Clause0_Int Clause0_Rat → Result (lattice.rat.Rat B
    Clause0_Int Clause0_Rat)

/-- [lattice::rat::{lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}::sign]:
    Source: 'crates/lattice/src/rat.rs', lines 332:4-332:28
    Name pattern: [lattice::rat::{lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>}::sign]
    Visibility: public -/
@[rust_fun
  "lattice::rat::{lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>}::sign"]
axiom lattice.rat.Rat.sign
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type} (backendBackendInst :
  lattice.backend.Backend B Clause0_Int Clause0_Rat) :
  lattice.rat.Rat B Clause0_Int Clause0_Rat → Result Std.I8

/-- [lattice::rat::{impl core::clone::Clone for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}::clone]:
    Source: 'crates/lattice/src/rat.rs', lines 467:4-467:27
    Name pattern: [lattice::rat::{core::clone::Clone<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>}::clone]
    Visibility: public -/
@[rust_fun
  "lattice::rat::{core::clone::Clone<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>}::clone"]
axiom lattice.rat.Rat.Insts.CoreCloneClone.clone
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type} (backendBackendInst :
  lattice.backend.Backend B Clause0_Int Clause0_Rat) :
  lattice.rat.Rat B Clause0_Int Clause0_Rat → Result (lattice.rat.Rat B
    Clause0_Int Clause0_Rat)

/-- [lattice::rat::{impl core::cmp::PartialEq<lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>> for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}::eq]:
    Source: 'crates/lattice/src/rat.rs', lines 475:4-475:34
    Name pattern: [lattice::rat::{core::cmp::PartialEq<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>, lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>}::eq]
    Visibility: public -/
@[rust_fun
  "lattice::rat::{core::cmp::PartialEq<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>, lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>}::eq"]
axiom lattice.rat.Rat.Insts.CoreCmpPartialEqRat.eq
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type} (backendBackendInst :
  lattice.backend.Backend B Clause0_Int Clause0_Rat) :
  lattice.rat.Rat B Clause0_Int Clause0_Rat → lattice.rat.Rat B Clause0_Int
    Clause0_Rat → Result Bool

/-- [lattice::rat::{impl core::cmp::PartialOrd<lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>> for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}::partial_cmp]:
    Source: 'crates/lattice/src/rat.rs', lines 481:4-481:55
    Name pattern: [lattice::rat::{core::cmp::PartialOrd<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>, lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "lattice::rat::{core::cmp::PartialOrd<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>, lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>}::partial_cmp"]
axiom lattice.rat.Rat.Insts.CoreCmpPartialOrdRat.partial_cmp
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type} (backendBackendInst :
  lattice.backend.Backend B Clause0_Int Clause0_Rat) :
  lattice.rat.Rat B Clause0_Int Clause0_Rat → lattice.rat.Rat B Clause0_Int
    Clause0_Rat → Result (Option Ordering)

/-- [lattice::rat::{impl core::cmp::Ord for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}::cmp]:
    Source: 'crates/lattice/src/rat.rs', lines 486:4-486:39
    Name pattern: [lattice::rat::{core::cmp::Ord<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>}::cmp]
    Visibility: public -/
@[rust_fun
  "lattice::rat::{core::cmp::Ord<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>}::cmp"]
axiom lattice.rat.Rat.Insts.CoreCmpOrd.cmp
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type} (backendBackendInst :
  lattice.backend.Backend B Clause0_Int Clause0_Rat) :
  lattice.rat.Rat B Clause0_Int Clause0_Rat → lattice.rat.Rat B Clause0_Int
    Clause0_Rat → Result Ordering

