-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lattice]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Lattice.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open lattice

/-- [core::cmp::{impl core::cmp::PartialEq<core::cmp::Ordering> for core::cmp::Ordering}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 398:43-398:52
    Name pattern: [core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq]
    Visibility: public -/
@[rust_fun
  "core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq"]
axiom core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq
  : Ordering → Ordering → Result Bool

/-- [core::convert::num::{impl core::convert::TryFrom<u128, core::num::error::TryFromIntError> for i128}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 300:12-300:64
    Name pattern: [core::convert::num::{core::convert::TryFrom<i128, u128, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::{core::convert::TryFrom<i128, u128, core::num::error::TryFromIntError>}::try_from"]
axiom I128.Insts.CoreConvertTryFromU128TryFromIntError.try_from
  :
  Std.U128 → Result (core.result.Result Std.I128
    core.num.error.TryFromIntError)

/-- [core::num::{i128}::checked_neg]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 1332:8-1332:54
    Name pattern: [core::num::{i128}::checked_neg]
    Visibility: public -/
@[rust_fun "core::num::{i128}::checked_neg"]
axiom core.num.I128.checked_neg : Std.I128 → Result (Option Std.I128)

/-- [core::num::{i128}::wrapping_neg]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 2363:8-2363:47
    Name pattern: [core::num::{i128}::wrapping_neg]
    Visibility: public -/
@[rust_fun "core::num::{i128}::wrapping_neg"]
axiom core.num.I128.wrapping_neg : Std.I128 → Result Std.I128

/-- [core::num::{i128}::unsigned_abs]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 2486:8-2486:53
    Name pattern: [core::num::{i128}::unsigned_abs]
    Visibility: public -/
@[rust_fun "core::num::{i128}::unsigned_abs"]
axiom core.num.I128.unsigned_abs : Std.I128 → Result Std.U128

/-- [core::num::{i128}::signum]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 3713:8-3713:41
    Name pattern: [core::num::{i128}::signum]
    Visibility: public -/
@[rust_fun "core::num::{i128}::signum"]
axiom core.num.I128.signum : Std.I128 → Result Std.I128

/-- [core::num::{usize}::div_ceil]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3755:8-3755:54
    Name pattern: [core::num::{usize}::div_ceil]
    Visibility: public -/
@[rust_fun "core::num::{usize}::div_ceil"]
axiom core.num.Usize.div_ceil : Std.Usize → Std.Usize → Result Std.Usize

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [core::result::{core::result::Result<T, E>}::ok]:
    Source: '/rustc/library/core/src/result.rs', lines 708:4-711:28
    Name pattern: [core::result::{core::result::Result<@T, @E>}::ok]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::ok"]
axiom core.result.Result.ok
  {T : Type} {E : Type} : core.result.Result T E → Result (Option T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2850:4-2850:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3085:4-3085:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

