-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [certify_core]: function definitions
import Aeneas
import CertifyCore.Types
import CertifyCore.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace certify_core

/-- Trait implementation: [core::cmp::{impl core::cmp::PartialEq<core::cmp::Ordering> for core::cmp::Ordering}]
    Source: '/rustc/library/core/src/cmp.rs', lines 398:43-398:52
    Name pattern: [core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>"]
impl_def core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering : core.cmp.PartialEq
  Ordering Ordering := {
  eq := core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq
  ne := core.cmp.PartialEq.ne.trait_default
    core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering
}

/-- Trait implementation: [lattice::rat::{impl core::clone::Clone for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}]
    Source: 'crates/lattice/src/rat.rs', lines 347:0-347:33
    Name pattern: [core::clone::Clone<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>] -/
@[reducible, rust_trait_impl
  "core::clone::Clone<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>"]
def lattice.rat.Rat.Insts.CoreCloneClone {B : Type} {Clause0_Int : Type}
  {Clause0_Rat : Type} (backendBackendInst : lattice.backend.Backend B
  Clause0_Int Clause0_Rat) : core.clone.Clone (lattice.rat.Rat B Clause0_Int
  Clause0_Rat) := {
  clone := lattice.rat.Rat.Insts.CoreCloneClone.clone backendBackendInst
}

/-- Trait implementation: [lattice::rat::{impl core::cmp::PartialEq<lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>> for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}]
    Source: 'crates/lattice/src/rat.rs', lines 355:0-355:37
    Name pattern: [core::cmp::PartialEq<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>, lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>, lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>"]
impl_def lattice.rat.Rat.Insts.CoreCmpPartialEqRat {B : Type} {Clause0_Int :
  Type} {Clause0_Rat : Type} (backendBackendInst : lattice.backend.Backend B
  Clause0_Int Clause0_Rat) : core.cmp.PartialEq (lattice.rat.Rat B Clause0_Int
  Clause0_Rat) (lattice.rat.Rat B Clause0_Int Clause0_Rat) := {
  eq := lattice.rat.Rat.Insts.CoreCmpPartialEqRat.eq backendBackendInst
  ne := core.cmp.PartialEq.ne.trait_default
    (lattice.rat.Rat.Insts.CoreCmpPartialEqRat backendBackendInst)
}

/-- Trait implementation: [lattice::rat::{impl core::cmp::Eq for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}]
    Source: 'crates/lattice/src/rat.rs', lines 360:0-360:30
    Name pattern: [core::cmp::Eq<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>] -/
@[reducible, rust_trait_impl
  "core::cmp::Eq<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>"]
def lattice.rat.Rat.Insts.CoreCmpEq {B : Type} {Clause0_Int : Type}
  {Clause0_Rat : Type} (backendBackendInst : lattice.backend.Backend B
  Clause0_Int Clause0_Rat) : core.cmp.Eq (lattice.rat.Rat B Clause0_Int
  Clause0_Rat) := {
  partialEqInst := lattice.rat.Rat.Insts.CoreCmpPartialEqRat backendBackendInst
}

/-- Trait implementation: [lattice::rat::{impl core::cmp::PartialOrd<lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>> for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}]
    Source: 'crates/lattice/src/rat.rs', lines 361:0-361:38
    Name pattern: [core::cmp::PartialOrd<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>, lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialOrd<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>, lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>"]
def lattice.rat.Rat.Insts.CoreCmpPartialOrdRat {B : Type} {Clause0_Int : Type}
  {Clause0_Rat : Type} (backendBackendInst : lattice.backend.Backend B
  Clause0_Int Clause0_Rat) : core.cmp.PartialOrd (lattice.rat.Rat B Clause0_Int
  Clause0_Rat) (lattice.rat.Rat B Clause0_Int Clause0_Rat) := {
  partialEqInst := lattice.rat.Rat.Insts.CoreCmpPartialEqRat backendBackendInst
  partial_cmp := lattice.rat.Rat.Insts.CoreCmpPartialOrdRat.partial_cmp
    backendBackendInst
}

/-- Trait implementation: [lattice::rat::{impl core::cmp::Ord for lattice::rat::Rat<B, Clause0_Int, Clause0_Rat>}]
    Source: 'crates/lattice/src/rat.rs', lines 366:0-366:31
    Name pattern: [core::cmp::Ord<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>] -/
@[reducible, rust_trait_impl
  "core::cmp::Ord<lattice::rat::Rat<@B, @Clause0_Int, @Clause0_Rat>>"]
def lattice.rat.Rat.Insts.CoreCmpOrd {B : Type} {Clause0_Int : Type}
  {Clause0_Rat : Type} (backendBackendInst : lattice.backend.Backend B
  Clause0_Int Clause0_Rat) : core.cmp.Ord (lattice.rat.Rat B Clause0_Int
  Clause0_Rat) := {
  eqInst := lattice.rat.Rat.Insts.CoreCmpEq backendBackendInst
  partialOrdInst := lattice.rat.Rat.Insts.CoreCmpPartialOrdRat
    backendBackendInst
  cmp := lattice.rat.Rat.Insts.CoreCmpOrd.cmp backendBackendInst
}

/-- [certify_core::arrange::cyclic_true_runs]: loop body 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 104:4-110:5 -/
@[rust_loop_body]
def arrange.cyclic_true_runs_loop.body
  (sectors : Slice Bool) (n : Std.Usize) (runs : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) Std.Usize)
  := do
  if i < n
  then
    let b ← Slice.index_usize sectors i
    let runs1 ←
      if b
      then
        do
        let i1 ← i + n
        let i2 ← i1 - 1#usize
        let i3 ← i2 % n
        let b1 ← Slice.index_usize sectors i3
        if b1
        then ok runs
        else runs + 1#usize
      else ok runs
    let i1 ← i + 1#usize
    ok (cont (runs1, i1))
  else ok (done runs)

/-- [certify_core::arrange::cyclic_true_runs]: loop 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 104:4-110:5 -/
@[rust_loop]
def arrange.cyclic_true_runs_loop
  (sectors : Slice Bool) (n : Std.Usize) (runs : Std.Usize) (i : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (runs1, i1) => arrange.cyclic_true_runs_loop.body sectors n runs1 i1)
    (runs, i)

/-- [certify_core::arrange::cyclic_true_runs]:
    Source: 'crates/certify-core/src/arrange.rs', lines 97:0-113:1 -/
def arrange.cyclic_true_runs (sectors : Slice Bool) : Result Std.Usize := do
  let n := Slice.len sectors
  if n = 0#usize
  then ok 0#usize
  else
    let runs ← arrange.cyclic_true_runs_loop sectors n 0#usize 0#usize
    if runs = 0#usize
    then
      let b ← Slice.index_usize sectors 0#usize
      if b
      then ok 1#usize
      else ok runs
    else ok runs

/-- [certify_core::arrange::all_true]: loop body 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 136:4-143:1 -/
@[rust_loop_body]
def arrange.all_true_loop.body
  (sectors : Slice Bool) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len sectors
  if i < i1
  then
    let b ← Slice.index_usize sectors i
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else ok (done false)
  else ok (done true)

/-- [certify_core::arrange::all_true]: loop 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 136:4-143:1 -/
@[rust_loop]
def arrange.all_true_loop
  (sectors : Slice Bool) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => arrange.all_true_loop.body sectors i1)
    i

/-- [certify_core::arrange::all_true]:
    Source: 'crates/certify-core/src/arrange.rs', lines 134:0-143:1 -/
@[reducible]
def arrange.all_true (sectors : Slice Bool) : Result Bool := do
  arrange.all_true_loop sectors 0#usize

/-- [certify_core::arrange::classify_link]:
    Source: 'crates/certify-core/src/arrange.rs', lines 119:0-131:1
    Visibility: public -/
def arrange.classify_link
  (sectors : Slice Bool) : Result arrange.LinkClass := do
  let i ← arrange.cyclic_true_runs sectors
  match i.val with
  | 0 => ok arrange.LinkClass.Exterior
  | 1 =>
    let b ← arrange.all_true sectors
    if b
    then ok arrange.LinkClass.Interior
    else ok arrange.LinkClass.Boundary
  | _ => ok arrange.LinkClass.Pinch

/-- [certify_core::arrange::v_boundary]:
    Source: 'crates/certify-core/src/arrange.rs', lines 147:0-149:1
    Visibility: public -/
def arrange.v_boundary (sectors : Slice Bool) : Result Bool := do
  let lc ← arrange.classify_link sectors
  match lc with
  | arrange.LinkClass.Exterior => ok false
  | arrange.LinkClass.Interior => ok false
  | arrange.LinkClass.Boundary => ok true
  | arrange.LinkClass.Pinch => ok false

/-- [certify_core::arrange::link_ok]:
    Source: 'crates/certify-core/src/arrange.rs', lines 153:0-155:1
    Visibility: public -/
def arrange.link_ok (sectors : Slice Bool) : Result Bool := do
  let lc ← arrange.classify_link sectors
  let b ←
    match lc with
    | arrange.LinkClass.Exterior => ok false
    | arrange.LinkClass.Interior => ok false
    | arrange.LinkClass.Boundary => ok false
    | arrange.LinkClass.Pinch => ok true
  ok (¬ b)

/-- [certify_core::arrange::link_iso_ok]: loop body 1:
    Source: 'crates/certify-core/src/arrange.rs', lines 177:8-183:9
    Visibility: public -/
@[rust_loop_body]
def arrange.link_iso_ok_loop0_loop0.body
  (a : Slice Std.Usize) (b : Slice Std.Usize) (n : Std.Usize) (off : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if i < n
  then
    let i1 ← Slice.index_usize a i
    let i2 ← i + off
    let i3 ← i2 % n
    let i4 ← Slice.index_usize b i3
    if i1 != i4
    then ok (done false)
    else let i5 ← i + 1#usize
         ok (cont i5)
  else ok (done true)

/-- [certify_core::arrange::link_iso_ok]: loop 1:
    Source: 'crates/certify-core/src/arrange.rs', lines 177:8-183:9
    Visibility: public -/
@[rust_loop]
def arrange.link_iso_ok_loop0_loop0
  (a : Slice Std.Usize) (b : Slice Std.Usize) (n : Std.Usize) (off : Std.Usize)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => arrange.link_iso_ok_loop0_loop0.body a b n off i1)
    i

/-- [certify_core::arrange::link_iso_ok]: loop body 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 174:4-190:1
    Visibility: public -/
@[rust_loop_body]
def arrange.link_iso_ok_loop0.body
  (a : Slice Std.Usize) (b : Slice Std.Usize) (n : Std.Usize) (off : Std.Usize)
  :
  Result (ControlFlow Std.Usize Bool)
  := do
  if off < n
  then
    let matched ← arrange.link_iso_ok_loop0_loop0 a b n off 0#usize
    if matched
    then ok (done true)
    else let off1 ← off + 1#usize
         ok (cont off1)
  else ok (done false)

/-- [certify_core::arrange::link_iso_ok]: loop 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 174:4-190:1
    Visibility: public -/
@[rust_loop]
def arrange.link_iso_ok_loop0
  (a : Slice Std.Usize) (b : Slice Std.Usize) (n : Std.Usize) (off : Std.Usize)
  :
  Result Bool
  := do
  loop
    (fun off1 => arrange.link_iso_ok_loop0.body a b n off1)
    off

/-- [certify_core::arrange::link_iso_ok]:
    Source: 'crates/certify-core/src/arrange.rs', lines 164:0-190:1
    Visibility: public -/
def arrange.link_iso_ok
  (a : Slice Std.Usize) (b : Slice Std.Usize) : Result Bool := do
  let n := Slice.len a
  let i := Slice.len b
  if i != n
  then ok false
  else if n = 0#usize
       then ok true
       else arrange.link_iso_ok_loop0 a b n 0#usize

/-- [certify_core::certify1d::corner_range]: loop body 0:
    Source: 'crates/certify-core/src/certify1d.rs', lines 127:8-130:9
    Visibility: public -/
@[rust_loop_body]
def certify1d.corner_range_loop.body
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (iter : core.slice.iter.Iter T) (lo : T) (hi : T) :
  Result (ControlFlow ((core.slice.iter.Iter T) × T × T) (T × T))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (lo, hi))
  | some c =>
    let o1 ← corecmpOrdInst.cmp c lo
    let b ←
      core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq o1 Ordering.lt
    let lo1 ← if b
                then corecloneCloneInst.clone c
                else ok lo
    let o2 ← corecmpOrdInst.cmp c hi
    let b1 ←
      core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq o2 Ordering.gt
    if b1
    then let hi1 ← corecloneCloneInst.clone c
         ok (cont (iter1, lo1, hi1))
    else ok (cont (iter1, lo1, hi))

/-- [certify_core::certify1d::corner_range]: loop 0:
    Source: 'crates/certify-core/src/certify1d.rs', lines 127:8-130:9
    Visibility: public -/
@[rust_loop]
def certify1d.corner_range_loop
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (iter : core.slice.iter.Iter T) (lo : T) (hi : T) :
  Result (T × T)
  := do
  loop
    (fun (iter1, lo1, hi1) => certify1d.corner_range_loop.body corecmpOrdInst
      corecloneCloneInst iter1 lo1 hi1)
    (iter, lo, hi)

/-- [certify_core::certify1d::corner_range]:
    Source: 'crates/certify-core/src/certify1d.rs', lines 123:0-136:1
    Visibility: public -/
def certify1d.corner_range
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (corners : Slice T) :
  Result (Option (T × T))
  := do
  let it ← core.slice.Slice.iter corners
  let (o, it1) ← core.slice.iter.IteratorSliceIter.next it
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let lo ← corecloneCloneInst.clone val
    let (lo1, hi) ←
      certify1d.corner_range_loop corecmpOrdInst corecloneCloneInst it1 lo lo
    ok (some (lo1, hi))
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      (T × T) residual

/-- [certify_core::certify1d::clip_sigma_branch]:
    Source: 'crates/certify-core/src/certify1d.rs', lines 222:0-238:1 -/
def certify1d.clip_sigma_branch
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (lo : T) (hi : T) (m : T)
  (neg_m : T) (m_positive : Bool) :
  Result (Option certify1d.ClipBranch)
  := do
  if m_positive
  then
    let o ← corecmpOrdInst.cmp lo m
    let b ←
      core.cmp.PartialEq.ne.trait_default
        core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering o Ordering.lt
    if b
    then ok (some certify1d.ClipBranch.Positive)
    else
      let o1 ← corecmpOrdInst.cmp hi neg_m
      let b1 ←
        core.cmp.PartialEq.ne.trait_default
          core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering o1 Ordering.gt
      if b1
      then ok (some certify1d.ClipBranch.Negative)
      else ok none
  else ok none

/-- [certify_core::certify1d::clip_sigma]:
    Source: 'crates/certify-core/src/certify1d.rs', lines 198:0-210:1
    Visibility: public -/
def certify1d.clip_sigma
  {B : Type} {Clause0_Int : Type} {Clause0_Rat : Type}
  (latticebackendBackendInst : lattice.backend.Backend B Clause0_Int
  Clause0_Rat) (cert : certify1d.ClipSigmaCert B Clause0_Int Clause0_Rat) :
  Result (verdict.Verdict certify1d.ClipBranch Unit (lattice.rat.Rat B
    Clause0_Int Clause0_Rat))
  := do
  let s ← lift (Array.to_slice cert.corners)
  let o ←
    certify1d.corner_range (lattice.rat.Rat.Insts.CoreCmpOrd
      latticebackendBackendInst) (lattice.rat.Rat.Insts.CoreCloneClone
      latticebackendBackendInst) s
  match o with
  | none =>
    let r ← lattice.rat.Rat.from_i128 latticebackendBackendInst 0#i128
    ok (verdict.Verdict.Unresolved r)
  | some r =>
    let (lo, hi) := r
    let neg_m ← lattice.rat.Rat.neg latticebackendBackendInst cert.m_sigma
    let i ← lattice.rat.Rat.sign latticebackendBackendInst cert.m_sigma
    let o1 ←
      certify1d.clip_sigma_branch (lattice.rat.Rat.Insts.CoreCmpOrd
        latticebackendBackendInst) lo hi cert.m_sigma neg_m (i > 0#i8)
    match o1 with
    | none =>
      let r1 ← lattice.rat.Rat.sub latticebackendBackendInst hi lo
      ok (verdict.Verdict.Unresolved r1)
    | some branch => ok (verdict.Verdict.Verified branch)

end certify_core
