-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [certify_core]: function definitions
import Aeneas
import CertifyCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace certify_core

/-- [certify_core::arrange::cyclic_true_runs]: loop body 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 99:4-105:5 -/
@[rust_loop_body]
def arrange.cyclic_true_runs_loop.body
  (sectors : Slice Bool) (n : Std.Usize) (runs : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) Std.Usize)
  := do
  if i < n
  then
    let b ← Slice.index_usize sectors i
    let runs1 ←
      if b
      then
        do
        let i1 ← i + n
        let i2 ← i1 - 1#usize
        let i3 ← i2 % n
        let b1 ← Slice.index_usize sectors i3
        if b1
        then ok runs
        else runs + 1#usize
      else ok runs
    let i1 ← i + 1#usize
    ok (cont (runs1, i1))
  else ok (done runs)

/-- [certify_core::arrange::cyclic_true_runs]: loop 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 99:4-105:5 -/
@[rust_loop]
def arrange.cyclic_true_runs_loop
  (sectors : Slice Bool) (n : Std.Usize) (runs : Std.Usize) (i : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (runs1, i1) => arrange.cyclic_true_runs_loop.body sectors n runs1 i1)
    (runs, i)

/-- [certify_core::arrange::cyclic_true_runs]:
    Source: 'crates/certify-core/src/arrange.rs', lines 92:0-108:1 -/
def arrange.cyclic_true_runs (sectors : Slice Bool) : Result Std.Usize := do
  let n := Slice.len sectors
  if n = 0#usize
  then ok 0#usize
  else
    let runs ← arrange.cyclic_true_runs_loop sectors n 0#usize 0#usize
    if runs = 0#usize
    then
      let b ← Slice.index_usize sectors 0#usize
      if b
      then ok 1#usize
      else ok runs
    else ok runs

/-- [certify_core::arrange::all_true]: loop body 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 131:4-138:1 -/
@[rust_loop_body]
def arrange.all_true_loop.body
  (sectors : Slice Bool) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len sectors
  if i < i1
  then
    let b ← Slice.index_usize sectors i
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else ok (done false)
  else ok (done true)

/-- [certify_core::arrange::all_true]: loop 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 131:4-138:1 -/
@[rust_loop]
def arrange.all_true_loop
  (sectors : Slice Bool) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => arrange.all_true_loop.body sectors i1)
    i

/-- [certify_core::arrange::all_true]:
    Source: 'crates/certify-core/src/arrange.rs', lines 129:0-138:1 -/
@[reducible]
def arrange.all_true (sectors : Slice Bool) : Result Bool := do
  arrange.all_true_loop sectors 0#usize

/-- [certify_core::arrange::classify_link]:
    Source: 'crates/certify-core/src/arrange.rs', lines 114:0-126:1
    Visibility: public -/
def arrange.classify_link
  (sectors : Slice Bool) : Result arrange.LinkClass := do
  let i ← arrange.cyclic_true_runs sectors
  match i.val with
  | 0 => ok arrange.LinkClass.Exterior
  | 1 =>
    let b ← arrange.all_true sectors
    if b
    then ok arrange.LinkClass.Interior
    else ok arrange.LinkClass.Boundary
  | _ => ok arrange.LinkClass.Pinch

/-- [certify_core::arrange::v_boundary]:
    Source: 'crates/certify-core/src/arrange.rs', lines 142:0-144:1
    Visibility: public -/
def arrange.v_boundary (sectors : Slice Bool) : Result Bool := do
  let lc ← arrange.classify_link sectors
  match lc with
  | arrange.LinkClass.Exterior => ok false
  | arrange.LinkClass.Interior => ok false
  | arrange.LinkClass.Boundary => ok true
  | arrange.LinkClass.Pinch => ok false

/-- [certify_core::arrange::link_ok]:
    Source: 'crates/certify-core/src/arrange.rs', lines 148:0-150:1
    Visibility: public -/
def arrange.link_ok (sectors : Slice Bool) : Result Bool := do
  let lc ← arrange.classify_link sectors
  let b ←
    match lc with
    | arrange.LinkClass.Exterior => ok false
    | arrange.LinkClass.Interior => ok false
    | arrange.LinkClass.Boundary => ok false
    | arrange.LinkClass.Pinch => ok true
  ok (¬ b)

/-- [certify_core::arrange::link_iso_ok]: loop body 1:
    Source: 'crates/certify-core/src/arrange.rs', lines 172:8-178:9
    Visibility: public -/
@[rust_loop_body]
def arrange.link_iso_ok_loop0_loop0.body
  (a : Slice Std.Usize) (b : Slice Std.Usize) (n : Std.Usize) (off : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if i < n
  then
    let i1 ← Slice.index_usize a i
    let i2 ← i + off
    let i3 ← i2 % n
    let i4 ← Slice.index_usize b i3
    if i1 != i4
    then ok (done false)
    else let i5 ← i + 1#usize
         ok (cont i5)
  else ok (done true)

/-- [certify_core::arrange::link_iso_ok]: loop 1:
    Source: 'crates/certify-core/src/arrange.rs', lines 172:8-178:9
    Visibility: public -/
@[rust_loop]
def arrange.link_iso_ok_loop0_loop0
  (a : Slice Std.Usize) (b : Slice Std.Usize) (n : Std.Usize) (off : Std.Usize)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => arrange.link_iso_ok_loop0_loop0.body a b n off i1)
    i

/-- [certify_core::arrange::link_iso_ok]: loop body 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 169:4-185:1
    Visibility: public -/
@[rust_loop_body]
def arrange.link_iso_ok_loop0.body
  (a : Slice Std.Usize) (b : Slice Std.Usize) (n : Std.Usize) (off : Std.Usize)
  :
  Result (ControlFlow Std.Usize Bool)
  := do
  if off < n
  then
    let matched ← arrange.link_iso_ok_loop0_loop0 a b n off 0#usize
    if matched
    then ok (done true)
    else let off1 ← off + 1#usize
         ok (cont off1)
  else ok (done false)

/-- [certify_core::arrange::link_iso_ok]: loop 0:
    Source: 'crates/certify-core/src/arrange.rs', lines 169:4-185:1
    Visibility: public -/
@[rust_loop]
def arrange.link_iso_ok_loop0
  (a : Slice Std.Usize) (b : Slice Std.Usize) (n : Std.Usize) (off : Std.Usize)
  :
  Result Bool
  := do
  loop
    (fun off1 => arrange.link_iso_ok_loop0.body a b n off1)
    off

/-- [certify_core::arrange::link_iso_ok]:
    Source: 'crates/certify-core/src/arrange.rs', lines 159:0-185:1
    Visibility: public -/
def arrange.link_iso_ok
  (a : Slice Std.Usize) (b : Slice Std.Usize) : Result Bool := do
  let n := Slice.len a
  let i := Slice.len b
  if i != n
  then ok false
  else if n = 0#usize
       then ok true
       else arrange.link_iso_ok_loop0 a b n 0#usize

end certify_core
