-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [certify_core]: type definitions
import Aeneas
import CertifyCore.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace certify_core

/-- Trait declaration: [lattice::backend::Backend]
    Source: 'crates/lattice/src/backend.rs', lines 33:0-33:17
    Name pattern: [lattice::backend::Backend]
    Visibility: public -/
@[rust_trait "lattice::backend::Backend"]
structure lattice.backend.Backend (Self : Type) (Self_Int : Type) (Self_Rat :
  Type) where
  int_clone : Self_Int → Result Self_Int
  rat_clone : Self_Rat → Result Self_Rat
  int_zero : Result Self_Int
  int_one : Result Self_Int
  int_from_i128 : Std.I128 → Result Self_Int
  int_try_to_i128 : Self_Int → Result (Option Std.I128)
  int_add : Self_Int → Self_Int → Result Self_Int
  int_sub : Self_Int → Self_Int → Result Self_Int
  int_mul : Self_Int → Self_Int → Result Self_Int
  int_neg : Self_Int → Result Self_Int
  int_cmp : Self_Int → Self_Int → Result Ordering
  int_sign : Self_Int → Result Std.I8
  int_is_zero : Self_Int → Result Bool
  int_gcd : Self_Int → Self_Int → Result Self_Int
  int_lcm : Self_Int → Self_Int → Result Self_Int
  int_divrem : Self_Int → Self_Int → Result (Self_Int × Self_Int)
  rat_from_i128 : Std.I128 → Result Self_Rat
  rat_from_ints : Self_Int → Self_Int → Result Self_Rat
  rat_add : Self_Rat → Self_Rat → Result Self_Rat
  rat_sub : Self_Rat → Self_Rat → Result Self_Rat
  rat_mul : Self_Rat → Self_Rat → Result Self_Rat
  rat_div : Self_Rat → Self_Rat → Result Self_Rat
  rat_neg : Self_Rat → Result Self_Rat
  rat_cmp : Self_Rat → Self_Rat → Result Ordering
  rat_sign : Self_Rat → Result Std.I8
  rat_is_zero : Self_Rat → Result Bool
  rat_numer : Self_Rat → Result Self_Int
  rat_denom : Self_Rat → Result Self_Int

/-- [certify_core::arrange::LinkClass]
    Source: 'crates/certify-core/src/arrange.rs', lines 102:0-116:1
    Visibility: public -/
@[discriminant isize]
inductive arrange.LinkClass where
| Exterior : arrange.LinkClass
| Interior : arrange.LinkClass
| Boundary : arrange.LinkClass
| Pinch : arrange.LinkClass

/-- [certify_core::certify1d::ClipBranch]
    Source: 'crates/certify-core/src/certify1d.rs', lines 199:0-206:1
    Visibility: public -/
@[discriminant isize]
inductive certify1d.ClipBranch where
| Positive : certify1d.ClipBranch
| Negative : certify1d.ClipBranch

/-- [certify_core::certify1d::ClipSigmaCert]
    Source: 'crates/certify-core/src/certify1d.rs', lines 210:0-219:1
    Visibility: public -/
structure certify1d.ClipSigmaCert (B : Type) (Clause0_Int : Type) (Clause0_Rat
  : Type) where
  corners : Array (lattice.rat.Rat B Clause0_Int Clause0_Rat) 4#usize
  m_sigma : lattice.rat.Rat B Clause0_Int Clause0_Rat

/-- [certify_core::verdict::Verdict]
    Source: 'crates/certify-core/src/verdict.rs', lines 13:0-17:1
    Visibility: public -/
@[discriminant isize]
inductive verdict.Verdict (E : Type) (W : Type) (M : Type) where
| Verified : E → verdict.Verdict E W M
| Refuted : W → verdict.Verdict E W M
| Unresolved : M → verdict.Verdict E W M

end certify_core
