-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [certify_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace certify_core

/-- [certify_core::arrange::LinkClass]
    Source: 'crates/certify-core/src/arrange.rs', lines 76:0-88:1
    Visibility: public -/
@[discriminant isize]
inductive arrange.LinkClass where
| Exterior : arrange.LinkClass
| Interior : arrange.LinkClass
| Boundary : arrange.LinkClass
| Pinch : arrange.LinkClass

end certify_core
