-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lattice]: function definitions
import Aeneas
import Lattice.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace lattice

/-- [lattice::sturm::sign_variations]: loop body 0:
    Source: 'crates/lattice/src/sturm.rs', lines 29:4-36:5
    Visibility: public -/
@[rust_loop_body]
def sturm.sign_variations_loop.body
  (iter : core.slice.iter.Iter Std.I8) (last : Std.I8) (v : Std.U32) :
  Result (ControlFlow ((core.slice.iter.Iter Std.I8) × Std.I8 × Std.U32)
    Std.U32)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done v)
  | some s =>
    if s != 0#i8
    then
      if last != 0#i8
      then
        if s != last
        then let v1 ← v + 1#u32
             ok (cont (iter1, s, v1))
        else ok (cont (iter1, s, v))
      else ok (cont (iter1, s, v))
    else ok (cont (iter1, last, v))

/-- [lattice::sturm::sign_variations]: loop 0:
    Source: 'crates/lattice/src/sturm.rs', lines 29:4-36:5
    Visibility: public -/
@[rust_loop]
def sturm.sign_variations_loop
  (iter : core.slice.iter.Iter Std.I8) (last : Std.I8) (v : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, last1, v1) => sturm.sign_variations_loop.body iter1 last1 v1)
    (iter, last, v)

/-- [lattice::sturm::sign_variations]:
    Source: 'crates/lattice/src/sturm.rs', lines 26:0-38:1
    Visibility: public -/
def sturm.sign_variations (signs : Slice Std.I8) : Result Std.U32 := do
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter
      signs
  sturm.sign_variations_loop iter 0#i8 0#u32

end lattice
