-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lattice]: type definitions
import Aeneas
import Lattice.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace lattice

/-- Trait declaration: [lattice::backend::Backend]
    Source: 'crates/lattice/src/backend.rs', lines 33:0-129:1
    Visibility: public -/
structure backend.Backend (Self : Type) (Self_Int : Type) (Self_Rat : Type)
  where
  int_clone : Self_Int → Result Self_Int
  rat_clone : Self_Rat → Result Self_Rat
  int_zero : Result Self_Int
  int_one : Result Self_Int
  int_from_i128 : Std.I128 → Result Self_Int
  int_try_to_i128 : Self_Int → Result (Option Std.I128)
  int_add : Self_Int → Self_Int → Result Self_Int
  int_sub : Self_Int → Self_Int → Result Self_Int
  int_mul : Self_Int → Self_Int → Result Self_Int
  int_neg : Self_Int → Result Self_Int
  int_cmp : Self_Int → Self_Int → Result Ordering
  int_sign : Self_Int → Result Std.I8
  int_is_zero : Self_Int → Result Bool
  int_gcd : Self_Int → Self_Int → Result Self_Int
  int_lcm : Self_Int → Self_Int → Result Self_Int
  int_divrem : Self_Int → Self_Int → Result (Self_Int × Self_Int)
  int_div : Self_Int → Self_Int → Result Self_Int
  int_rem : Self_Int → Self_Int → Result Self_Int
  rat_from_i128 : Std.I128 → Result Self_Rat
  rat_from_ints : Self_Int → Self_Int → Result Self_Rat
  rat_add : Self_Rat → Self_Rat → Result Self_Rat
  rat_sub : Self_Rat → Self_Rat → Result Self_Rat
  rat_mul : Self_Rat → Self_Rat → Result Self_Rat
  rat_div : Self_Rat → Self_Rat → Result Self_Rat
  rat_neg : Self_Rat → Result Self_Rat
  rat_cmp : Self_Rat → Self_Rat → Result Ordering
  rat_sign : Self_Rat → Result Std.I8
  rat_is_zero : Self_Rat → Result Bool
  rat_numer : Self_Rat → Result Self_Int
  rat_denom : Self_Rat → Result Self_Int

/-- [lattice::refbackend::RefNat]
    Source: 'crates/lattice/src/refbackend.rs', lines 26:0-28:1
    Visibility: public -/
structure refbackend.RefNat where
  limbs : alloc.vec.Vec Std.U64

/-- [lattice::refbackend::RefInt]
    Source: 'crates/lattice/src/refbackend.rs', lines 259:0-262:1
    Visibility: public -/
structure refbackend.RefInt where
  neg : Bool
  mag : refbackend.RefNat

/-- [lattice::refbackend::RefRat]
    Source: 'crates/lattice/src/refbackend.rs', lines 330:0-333:1
    Visibility: public -/
structure refbackend.RefRat where
  num : refbackend.RefInt
  den : refbackend.RefNat

/-- [lattice::refbackend::RefBackend]
    Source: 'crates/lattice/src/refbackend.rs', lines 366:0-366:22
    Visibility: public -/
@[reducible]
def refbackend.RefBackend := Unit

/-- [lattice::small::SmallRat]
    Source: 'crates/lattice/src/small.rs', lines 39:0-42:1
    Visibility: public -/
structure small.SmallRat where
  num : Std.I128
  den : Std.I128

end lattice
