-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lattice]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace lattice

/-- [lattice::small::SmallRat]
    Source: 'crates/lattice/src/small.rs', lines 39:0-42:1
    Visibility: public -/
structure small.SmallRat where
  num : Std.I128
  den : Std.I128

end lattice
